# Generated by Django 6.0.2 on 2026-02-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantcard',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
