# Generated by Django 6.0.2 on 2026-02-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='elapsed_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
