# Generated by Django 6.0.2 on 2026-02-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0004_chatmessage_elapsed_ms_chatmessage_tokens_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_predefined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-usage_count', '-last_used'],
                'indexes': [models.Index(fields=['prompt'], name='agent_app_p_prompt_bdf6ff_idx'), models.Index(fields=['-usage_count', '-last_used'], name='agent_app_p_usage_c_2c1a77_idx')],
            },
        ),
    ]
