# Generated by Django 6.0.2 on 2026-02-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0005_promptsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback_comment',
            field=models.TextField(blank=True),
        ),
    ]
