# Generated by Django 6.0.2 on 2026-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0006_chatmessage_feedback_chatmessage_feedback_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('selected_agent', models.CharField(choices=[('gres', 'GRES Agent'), ('sam', 'SAM.gov Exclusions')], default='gres', max_length=50)),
                ('selected_model', models.CharField(choices=[('claude-3-5-sonnet', 'Claude 3.5 Sonnet'), ('claude-3-5-opus', 'Claude 3.5 Opus'), ('claude-3-haiku', 'Claude 3 Haiku')], default='claude-3-5-sonnet', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
