# Generated by Django 6.0.2 on 2026-02-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0007_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantcard',
            name='agent_type',
            field=models.CharField(choices=[('gres', 'GRES Agent'), ('sam', 'SAM.gov Agent'), ('all', 'All Agents')], default='gres', help_text='Which agent this card is for', max_length=50),
        ),
    ]
