# Generated by Django 6.0.2 on 2026-02-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0008_assistantcard_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantcard',
            name='agent_type',
            field=models.CharField(choices=[('gres', 'GRES Agent'), ('sam', 'SAM.gov Agent'), ('idv', 'Identity Verification'), ('all', 'All Agents')], default='gres', help_text='Which agent this card is for', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='selected_agent',
            field=models.CharField(choices=[('gres', 'GRES Agent'), ('sam', 'SAM.gov Exclusions'), ('idv', 'Identity Verification')], default='gres', max_length=50),
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name_hash', models.CharField(db_index=True, max_length=64)),
                ('city_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('state_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('is_valid', models.BooleanField()),
                ('fields_provided', models.JSONField()),
                ('verification_details', models.TextField()),
                ('requested_by_session', models.CharField(max_length=255)),
                ('requested_by_agent', models.CharField(default='idv', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-verification_date'],
                'indexes': [models.Index(fields=['name_hash', 'city_hash', 'state_hash'], name='agent_app_i_name_ha_82021c_idx'), models.Index(fields=['expiration_date', 'is_valid'], name='agent_app_i_expirat_c42112_idx')],
            },
        ),
    ]
