# Generated by Django 6.0.2 on 2026-02-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0010_alter_assistantcard_agent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='saved_prompts',
            field=models.TextField(blank=True, help_text='JSON-encoded saved prompts', null=True),
        ),
    ]
