# Generated by Django 6.0.2 on 2026-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0011_userpreference_saved_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantcard',
            name='agent_type',
            field=models.CharField(choices=[('gres', 'GRES Agent'), ('sam', 'SAM.gov Agent'), ('idv', 'Identity Verification'), ('library', 'Library Agent'), ('508', 'Section 508'), ('all', 'All Agents')], default='gres', help_text='Which agent this card is for', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='selected_agent',
            field=models.CharField(choices=[('gres', 'GRES Agent'), ('sam', 'SAM.gov Exclusions'), ('idv', 'Identity Verification'), ('library', 'Library Agent'), ('508', 'Section 508')], default='gres', max_length=50),
        ),
    ]
