# Generated by Django 6.0.2 on 2026-02-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0012_alter_assistantcard_agent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='section_508_enabled',
            field=models.BooleanField(default=False, help_text='Enable Section 508 accessibility features (TTS, high contrast, screen reader optimizations)'),
        ),
    ]
