# Generated by Django 6.0.2 on 2026-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0013_userpreference_section_508_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='section_508_enabled',
            field=models.BooleanField(blank=True, help_text='Enable Section 508 accessibility features (TTS, high contrast, screen reader optimizations). Null uses environment default.', null=True),
        ),
    ]
