# Generated by Django 6.0.2 on 2026-02-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0014_alter_userpreference_section_508_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio_url',
            field=models.CharField(blank=True, help_text='TTS audio URL for Section 508 mode', max_length=512, null=True),
        ),
    ]
