# Generated by Django 6.0.2 on 2026-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0015_chatmessage_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='context_message_count',
            field=models.IntegerField(default=0, help_text='Number of previous messages from current session to include as context (0 = no context, 20 = last 20 messages)'),
        ),
    ]
