# Generated by Django 5.2.11 on 2026-02-26 23:21

import agents.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0016_add_context_message_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='selected_model',
            field=models.CharField(choices=agents.base.get_django_model_choices, default='claude-haiku-4', max_length=100),
        ),
    ]
