# Generated by Django 5.2.11 on 2026-02-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0017_update_model_choices_to_claude_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantcard',
            name='agent_type',
            field=models.CharField(choices=[('gres', 'GRES Agent'), ('sam', 'SAM.gov Agent'), ('ofac', 'OFAC Compliance'), ('idv', 'Identity Verification'), ('library', 'Library Agent'), ('508', 'Section 508'), ('all', 'All Agents')], default='gres', help_text='Which agent this card is for', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='selected_agent',
            field=models.CharField(choices=[('gres', 'GRES Agent'), ('sam', 'SAM.gov Exclusions'), ('ofac', 'OFAC Compliance'), ('idv', 'Identity Verification'), ('library', 'Library Agent'), ('508', 'Section 508')], default='gres', max_length=50),
        ),
    ]
