# Generated by Django 5.2.11 on 2026-02-27 00:26

import agents.registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0018_add_ofac_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantcard',
            name='agent_type',
            field=models.CharField(choices=agents.registry.get_django_agent_choices, default=agents.registry.get_default_agent_id, help_text='Which agent this card is for', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='selected_agent',
            field=models.CharField(choices=agents.registry.get_django_agent_choices, default=agents.registry.get_default_agent_id, max_length=50),
        ),
    ]
