# Generated by Django 5.2.11 on 2026-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0019_alter_assistantcard_agent_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('run_id', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=100)),
                ('workflow_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('user_id', models.IntegerField(db_index=True, default=9)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('progress_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['user_id', '-started_at'], name='agent_app_w_user_id_71f965_idx'), models.Index(fields=['status', '-started_at'], name='agent_app_w_status_cc8f47_idx'), models.Index(fields=['workflow_id', '-started_at'], name='agent_app_w_workflo_56adc2_idx')],
            },
        ),
    ]
