# Generated by Django 5.2.11 on 2026-02-28 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0020_workflowrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('waiting_for_task', 'Waiting for Task')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='HumanTask',
            fields=[
                ('task_id', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('approval', 'Approval'), ('review', 'Review'), ('data_collection', 'Data Collection'), ('verification', 'Verification')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='open', max_length=20)),
                ('required_role', models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin')], db_index=True, default='user', max_length=20)),
                ('assigned_to_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agent_app.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='agent_app_h_status_41ceb4_idx'), models.Index(fields=['required_role', 'status', '-created_at'], name='agent_app_h_require_259df7_idx'), models.Index(fields=['workflow_run', '-created_at'], name='agent_app_h_workflo_161cc1_idx'), models.Index(fields=['expires_at', 'status'], name='agent_app_h_expires_35d7f7_idx'), models.Index(fields=['assigned_to_user_id', 'status'], name='agent_app_h_assigne_2a30de_idx')],
            },
        ),
    ]
