# Generated by Django 5.2.11 on 2026-03-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0021_alter_workflowrun_status_humantask'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user_id',
            field=models.IntegerField(db_index=True, default=9),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user_id',
            field=models.IntegerField(db_index=True, default=9),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='session_key',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user_id', '-created_at'], name='agent_app_c_user_id_3af166_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_key', 'user_id'], name='agent_app_c_session_607978_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user_id'], name='agent_app_u_user_id_45c8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['session_key', 'user_id'], name='agent_app_u_session_9783bf_idx'),
        ),
    ]
