# Generated by Django 5.2.11 on 2026-03-02 20:12

import agents.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0022_chatsession_user_id_userpreference_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humantask',
            name='completed_by_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='selected_model',
            field=models.CharField(choices=agents.base.get_django_model_choices, default='gpt-4o', max_length=100),
        ),
    ]
