# Generated by Django 5.2.11 on 2026-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0024_add_favorite_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(db_index=True, max_length=100)),
                ('version_number', models.IntegerField()),
                ('version_tag', models.CharField(blank=True, help_text="Tag like 'v1.0', 'stable', etc.", max_length=50, null=True)),
                ('created_by_user_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, help_text='Version description/changelog entry')),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='Mark if this is the active version')),
                ('version_path', models.CharField(help_text='Path to version folder relative to workflow directory', max_length=255)),
                ('metadata_checksum', models.CharField(help_text='SHA256 of metadata.yaml', max_length=64)),
                ('workflow_checksum', models.CharField(help_text='SHA256 of workflow.py', max_length=64)),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['workflow_id', '-version_number'], name='agent_app_w_workflo_78041f_idx'), models.Index(fields=['workflow_id', 'is_current'], name='agent_app_w_workflo_e2149a_idx'), models.Index(fields=['created_by_user_id', '-created_at'], name='agent_app_w_created_3f2ccd_idx')],
                'unique_together': {('workflow_id', 'version_number')},
            },
        ),
    ]
