# Generated by Django 5.2.11 on 2026-03-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0025_workflowversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('task_assigned', 'Task assigned'), ('task_due_soon', 'Task due soon'), ('workflow_completed', 'Workflow completed'), ('workflow_failed', 'Workflow failed')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('workflow_run_id', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='agent_app_n_user_id_e21370_idx'), models.Index(fields=['user_id', 'read_at'], name='agent_app_n_user_id_db4f35_idx')],
            },
        ),
    ]
