# Generated by Django 5.2.11 on 2026-03-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0026_add_notification_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('workflow_id', models.CharField(db_index=True, max_length=100)),
                ('run_name', models.CharField(blank=True, max_length=255)),
                ('input_data', models.JSONField(default=dict)),
                ('schedule_type', models.CharField(choices=[('once', 'Once'), ('interval', 'Interval')], max_length=20)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run_at'],
                'indexes': [models.Index(fields=['is_active', 'next_run_at'], name='agent_app_s_is_acti_444907_idx'), models.Index(fields=['user_id', '-created_at'], name='agent_app_s_user_id_8ef58b_idx')],
            },
        ),
    ]
