# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0027_scheduled_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='notification_preferences',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='e.g. {"notify_on_workflow_complete": true, "daily_digest": false}',
            ),
        ),
    ]
