# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_app", "0028_userpreference_notification_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workflow_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("workflow_number", models.PositiveIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["workflow_number"],
            },
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["workflow_number"], name="agent_app_w_workflo_idx"),
        ),
    ]
