# Generated by Django 5.2.5 on 2026-03-24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_app", "0030_workflowrun_bpmn_intermediate_wait_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(db_index=True, max_length=100, unique=True)),
                ("canonical_path", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["canonical_path"],
            },
        ),
        migrations.CreateModel(
            name="PageViewEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_time", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("canonical_path", models.CharField(db_index=True, max_length=255)),
                ("session_key_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("visitor_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("app_user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("referrer", models.CharField(blank=True, max_length=512)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("query_params_filtered", models.JSONField(blank=True, default=dict)),
                ("location_city", models.CharField(blank=True, max_length=120)),
                ("location_state", models.CharField(blank=True, max_length=120)),
                ("location_country", models.CharField(blank=True, db_index=True, max_length=120)),
                (
                    "location_source",
                    models.CharField(
                        choices=[("proxy_header", "Proxy header"), ("client", "Client"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "auth_user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "tracked_page",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="agent_app.trackedpage"),
                ),
            ],
            options={
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="TrackedPageQueryParam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("param_name", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tracked_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_query_params",
                        to="agent_app.trackedpage",
                    ),
                ),
            ],
            options={
                "ordering": ["param_name"],
                "unique_together": {("tracked_page", "param_name")},
            },
        ),
        migrations.AddIndex(
            model_name="trackedpage",
            index=models.Index(fields=["enabled", "canonical_path"], name="agent_app_t_enabled_4dc348_idx"),
        ),
        migrations.AddIndex(
            model_name="pageviewevent",
            index=models.Index(fields=["tracked_page", "-event_time"], name="agent_app_p_tracked_127f3b_idx"),
        ),
        migrations.AddIndex(
            model_name="pageviewevent",
            index=models.Index(fields=["canonical_path", "-event_time"], name="agent_app_p_canonic_b12762_idx"),
        ),
        migrations.AddIndex(
            model_name="pageviewevent",
            index=models.Index(fields=["app_user_id", "-event_time"], name="agent_app_p_app_use_8f75ef_idx"),
        ),
        migrations.AddIndex(
            model_name="pageviewevent",
            index=models.Index(fields=["visitor_id", "-event_time"], name="agent_app_p_visitor_0f7a69_idx"),
        ),
        migrations.AddIndex(
            model_name="trackedpagequeryparam",
            index=models.Index(fields=["tracked_page", "param_name"], name="agent_app_t_tracked_3ce0a9_idx"),
        ),
    ]

